networks:
  laravel:

volumes:
  mysqldata:
  redis:

services:
  php-cli:
    profiles:
      - donotstart
    build:
      context: ./dockerfiles
      dockerfile: php-cli.dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  queue:
    build:
      context: ./dockerfiles
      dockerfile: php-cli.dockerfile
    command: php artisan queue:listen --queue long-running,default,notifications
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  php-fpm:
    build:
      context: ./dockerfiles
      dockerfile: php-fpm.dockerfile
    ports:
      - '${APP_PORT:-9002}:9000'
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    restart: always
    shm_size: 256mb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
    networks:
      - laravel

  redis:
    image: redis:6
    restart: always
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - laravel
