name: CI/CD Workflow

on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: laravel_testing
          TZ: "UTC"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP and Node
        uses: ./.github/actions/setup-php-node

      - name: Run PHP Tests
        run: php artisan test --parallel --recreate-databases

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs

  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: laravel_testing
          TZ: "UTC"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP and Node
        uses: ./.github/actions/setup-php-node

      - name: Run lint
        run: npm run lint-fix

      - name: Run PHP CS Fixer
        run: composer fix

      - uses: EndBug/add-and-commit@v9.1.3
        with:
          add: '*.php *.tsx *.ts *.js'
          message: 'chore(style): Apply lint fix changes'

      - name: Build assets
        run: npm run build

      - name: Run compile
        run: npm run compile
