name: Setup PHP and Node
description: 'Reusable workflow to setup PHP and Node'

runs:
  using: 'composite'

  steps:
    - name: Cancel Previous Run
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache npm packages
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm-

    - name: Copy .env file
      shell: bash
      run: cp .env.ci .env

    - name: Install Composer Dependencies
      shell: bash
      run: composer install

    - name: Install npm dependencies
      shell: bash
      run: npm install

    - name: Configure application
      shell: bash
      run: |
        php artisan cache:clear
        php artisan config:clear
        php artisan key:generate

    - name: Generate Hybridly types
      shell: bash
      run: php artisan hybridly:types
